const ponoviBtn = document.querySelector('#ponoviBtn');
let odustaniBtn = document.querySelector('#odustani');
const postaviPitanje = document.querySelector('.pitanje');
let idOpcije = document.querySelector('#opcije');
let bingo = document.querySelectorAll('.bingo');
let h = document.querySelector('h1');
let abcd = ['* A: ','* B: ','* C: ','* D: '];
let points = document.querySelector('#points');
let zaSum = document.querySelectorAll('.belo');
let osvojiliSte = document.querySelector('#osvojiliSte');
let osvojenaSuma = document.querySelector('#osvojenaSuma');
let ukupnoPoena = document.querySelector('#ukupnoPoena');
let polaPolaBtn = document.querySelectorAll('.pomoc')[0];
let pomocPrijateljaBtn = document.querySelectorAll('.pomoc')[1];
let pomocPublikeBtn = document.querySelectorAll('.pomoc')[2];
let pomPrView = document.querySelector('#pomPrijatelja');
let col = document.querySelectorAll('.col');
let current;
let rand;
let brojac = 0;
let br1 = 0;
let br2 = 0;
let br3 = 0;
let seconds = 20;
let closse = document.querySelector('#closse');
let pomPublike = document.querySelector('#pomPublike');
